# Generated by Django 3.0.7 on 2021-09-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210915_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userComment',
            new_name='user_comment',
        ),
    ]
